services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "5000:8080"
      
  client:
    image: file-images
    build:
      context: .
      dockerfile: DokerfileClient
    container_name: client
    tty: true
    volumes:
      - local_images:/var/lib/images

    ports:
      - "8080:8080"   
      
  db:
    image: postgres:16
    container_name: local_pgdb
    restart: always
    ports:
      - "9000:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  nginx: #name of the fourth service
    container_name: loadbalancer_nginx
    build: loadbalancer # specify the directory of the Dockerfile
    restart: always
    ports:
      - "80:80" #specify ports forewarding
volumes:
  local_pgdata:
  pgadmin-data:
  local_images:  